allowBuilds:
  '@tsparticles/engine': true
  '@whiskeysockets/baileys': true
  esbuild: true
  msw: true
  protobufjs: true
  puppeteer: true
  sharp: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
overrides:
  browserslist: '>=4.28.7'
overrides:
  sharp: '>=0.35.5'
  source-map-js: '>=1.2.2'
